### GET = obtener lo que esta en la ip
###LISTAR TODO O / numero a seleccionar para ver por un solo dato
GET http://localhost:8000/api/empleado/

### UPDATE
PUT  http://localhost:8000/api/usuario/1
Content-Type: application/json

  {
    "nombre": "vendedor001",
    "password": "12345",
    "rol": "root"
  }

### insertar peticiones POST
POST http://localhost:8000/api/usuario
Content-Type: application/json

{
    "nombre": "vendedor002",
    "password": "11111",
    "rol": "empleado"
  }

### DELETE
DELETE http://localhost:8000/api/usuario/2


