### GET = obtener lo que esta en la ip
###LISTAR TODO O / numero a seleccionar para ver por un solo dato
http://localhost:3000/api/pedidos

### UPDATE
PUT  http://localhost:3000/api/pedidos/2
Content-Type: application/json

{
    "codigo_pedido": 1,
    "id_cliente": 2,
    "id_estado": 2
}

### insertar peticiones POST
POST http://localhost:3000/api/usuarios
Content-Type: application/json

  {
    "nombre": "root3",
    "cedula": 1144055179,
    "departamento": 24,
    "ciudad": 1009,
    "direccion": "cra47#15-22",
    "correo": "mov.com",
    "celular": 3112254525,
    "referido": "2",
    "rol": 1,
    "pass": 123456789
  }

### DELETE
DELETE http://localhost:3000/api/pedido/3


